[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
preDeployCommand = "python manage.py collectstatic --noinput && python manage.py migrate && python manage.py seed && python manage.py setup_schedules"
startCommand = "sh -c 'gunicorn playto.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 60'"
healthcheckPath = "/api/v1/merchants"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
