# Generated by Django 5.2.13 on 2026-04-25 05:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paise', models.BigIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('failure_reason', models.TextField(blank=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.bankaccount')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='ledger.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='payouts_pay_status_dd1f82_idx'), models.Index(fields=['merchant', 'created_at'], name='payouts_pay_merchan_c6a90f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='payout_amount_positive'), models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'])), name='payout_status_valid')],
            },
        ),
    ]
