# Migration files are auto-generated by `python manage.py makemigrations`.
# This file just marks the directory as a Python package.
#
# Generated migrations should be committed to git. The reviewer runs
# `python manage.py migrate` against a fresh database to set up.
#
# Never edit a migration that has already been applied to a deployed environment.
